version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - le-net
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend/react-docker
    ports:
      - "8080:80"
    networks:
      - le-net
    depends_on:
      - backend

networks:
  le-net:
    driver: bridge
