version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - le-net
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}

  frontend:
    build:
      context: ./frontend/react-docker
    ports:
      - "3000:3000"
    networks:
      - le-net
    depends_on:
      - backend

networks:
  le-net:
    driver: bridge