version: "3.8"

services:
  backend:
    # build:
    #   context: ./backend
    image: lichpeko/legal-ease-backend:trialTag
    ports:
      - "8000:8000"
    networks:
      - le-net
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend/react-docker
    ports:
      - "3000:3000"
    networks:
      - le-net
    # depends_on:
    #   - backend

networks:
  le-net:
    driver: bridge
